version: "3.0"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 12
    command: node example.js
    image: node:12
    environment:
      - PORT=4000
    ports:
      - "4001:4000"
    volumes:
      - .:/usr/src/app
    networks:
      - borneo
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 23101993
    ports:
      - "3307:3306"
    networks:
      - borneo
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - borneo
networks:
  borneo: